# Introduction

* Familiar with TensorFlow components `tf.Tensor`.
* Manage your own TensorFlow program (a `tf.Graph`)
* Run TensorFlow operations, using a `tf.Session`.

TensorFlow 的基本運算單位是張量（Tensor），零維張量等於是純量(Scalar)，一維張量是向量(Vector)，二維張量是矩陣(Matrix)等等。和Numpy相對比，ndarray（n 維陣列）觀念與 Tensor（n 維張量）觀念類似以外，TensorFlow 函數的命名、參數與設計概念都很接近 NumPy。

複習一下Tensorflow主要的運作流程分為以下兩個部分
* 建立模型(Build Model)
* 執行運算(Run)

Tensorflow設計的核心就是Tensor的流動，建立Graph的過程其實只是定義好Tensor如何流動並運算的過程，但真正的資料其實並沒有被運算，真正的計算需要用session來執行。
![graph](https://www.tensorflow.org/images/tensors_flowing.gif)

# Use tensorflow

In [1]:
%matplotlib inline

In [2]:
import numpy as np
import tensorflow as tf
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
print("TensorFlow version:", tf.__version__)
hw = tf.constant("Hello World")
print(hw)

TensorFlow version: 2.6.0
tf.Tensor(b'Hello World', shape=(), dtype=string)


In [4]:
if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using the GPU")
else:
  print("TensorFlow **IS NOT** using the GPU")

TensorFlow **IS** using the GPU


In [5]:

# Build a dataflow graph.
c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
d = tf.constant([[1.0, 1.0], [0.0, 1.0]])
e = tf.matmul(c, d)
print(e)



tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)


# What is tensor?

寫Tensorflow的程式其實就是在操縱Tensor物件，計算就是在講這些Tensor的流動。

`tf.Tensor` 有以下三種屬性(properties):

 * a data type (`float32`, `int32`, `complex64`,or `string`, for example)
 
 Use `dtype` to get data type attribute

 * a shape
 
 Use `shape` to get shape attribute

 * value
 
 Use `numpy()` method to get value of tensor.

同屬一個Tensor物件的所有元素都具有相同的資料屬性(data type)。而且建立Tensor物件時就會確定data type。

## About data type
The following DType objects are defined:

    * tf.float16: 16-bit half-precision floating-point.
    * tf.float32: 32-bit single-precision floating-point.
    * tf.float64: 64-bit double-precision floating-point.
    * tf.bfloat16: 16-bit truncated floating-point.
    * tf.complex64: 64-bit single-precision complex.
    * tf.complex128: 128-bit double-precision complex.
    * tf.int8: 8-bit signed integer.
    * tf.uint8: 8-bit unsigned integer.
    * tf.uint16: 16-bit unsigned integer.
    * tf.uint32: 32-bit unsigned integer.
    * tf.uint64: 64-bit unsigned integer.
    * tf.int16: 16-bit signed integer.
    * tf.int32: 32-bit signed integer.
    * tf.int64: 64-bit signed integer.
    * tf.bool: Boolean.
    * tf.string: String.
    * tf.qint8: Quantized 8-bit signed integer.
    * tf.quint8: Quantized 8-bit unsigned integer.
    * tf.qint16: Quantized 16-bit signed integer.
    * tf.quint16: Quantized 16-bit unsigned integer.
    * tf.qint32: Quantized 32-bit signed integer.
    * tf.resource: Handle to a mutable resource.
    * tf.variant: Values of arbitrary types.

## Rank

這裡講的Tensor rank和Tensor array的dimensions不同，前者講的是單一元素(element)的性質，後者講的是一群元素集合的性質。

Rank | Math entity
--- | ---
0 | Scalar (magnitude only)
1 | Vector (magnitude and direction)
2 | Matrix (table of numbers)
3 | 3-Tensor (cube of numbers)
n | n-Tensor (you get the idea)


Note that rank in TensorFlow is not the same as matrix rank in mathematics.

### Rank 0

"scalar" or "rank-0" tensor . A scalar contains a single value, and no "axes".

Note: A string is treated as a single object in TensorFlow, not as a sequence of
characters. It is possible to have scalar strings, vectors of strings, etc.

In [6]:
# This will be an int32 tensor by default; see "dtypes" below.
rank_0_tensor_int = tf.constant(4)
rank_0_tensor_str = tf.constant("Hello Tensorflow")
print("TensorFlow:")
print(rank_0_tensor_int)
print(rank_0_tensor_str)

TensorFlow:
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(b'Hello Tensorflow', shape=(), dtype=string)


In [7]:
rank_0_int=4
rank_0_str="Hello Tensorflow"

print("Python:")
print(type(rank_0_int))
print(type(rank_0_str))

Python:
<class 'int'>
<class 'str'>


### Rank 1

A "vector" or "rank-1" tensor is like a list of values. A vector has one axis:

To create a rank 1 `tf.Tensor` object, you can pass a list of items as the
initial value. For example:


In [8]:
# Let's make this a float tensor.
rank_1_tensor_float = tf.constant([2.0, 3.0, 4.0])
rank_1_tensor_complex = tf.constant([12.3 - 4.85j, 7.5 - 6.23j])
rank_1_tensor_str = tf.constant(["Hello"])
print("TensorFlow:")
print(rank_1_tensor_float)
print(rank_1_tensor_complex)
print(rank_1_tensor_str)

TensorFlow:
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor([12.3-4.85j  7.5-6.23j], shape=(2,), dtype=complex128)
tf.Tensor([b'Hello'], shape=(1,), dtype=string)


In [9]:
# Let's make this a float tensor.
rank_1_float = [2.0, 3.0, 4.0]
rank_1_complex = [12.3 - 4.85j, 7.5 - 6.23j]
rank_1_str = ["Hello"]
print("Python:")
print(type(rank_1_float))
print(type(rank_1_complex))
print(type(rank_1_str))

Python:
<class 'list'>
<class 'list'>
<class 'list'>


### Rank 2

A "matrix" or "rank-2" tensor has two axes:

A rank 2 `tf.Tensor` object consists of at least one row and at least
one column:

In [10]:
# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor_float = tf.constant([[1, 2],
                                   [3, 4],
                                   [5, 6]], dtype=tf.float16)
rank_2_tensor_int = tf.constant([[1, 2, 3, 4]], dtype=tf.int32)
rank_2_tensor_str = tf.constant([["Hellow"],
                                 ["Tensorflow"],
                                 ["!"]], dtype=tf.string)
print(rank_2_tensor_float)
print(rank_2_tensor_int)
print(rank_2_tensor_str)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)
tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[b'Hellow']
 [b'Tensorflow']
 [b'!']], shape=(3, 1), dtype=string)


<table>
<tr>
  <th>A scalar, shape: <code>[]</code></th>
  <th>A vector, shape: <code>[3]</code></th>
  <th>A matrix, shape: <code>[3, 2]</code></th>
</tr>
<tr>
  <td>
   <img src="./images/tensor/scalar.png" alt="A scalar, the number 4" />
  </td>

  <td>
   <img src="./images/tensor/vector.png" alt="The line with 3 sections, each one containing a number."/>
  </td>
  <td>
   <img src="./images/tensor/matrix.png" alt="A 3x2 grid, with each cell containing a number.">
  </td>
</tr>
</table>


### Rank 3
Tensors may have more axes; here is a tensor with three axes:

In [11]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


<table>
<tr>
  <th colspan=3>A 3-axis tensor, shape: <code>[3, 2, 5]</code></th>
<tr>
<tr>
  <td>
   <img src="images/tensor/3-axis_numpy.png"/>
  </td>
  <td>
   <img src="images/tensor/3-axis_front.png"/>
  </td>

  <td>
   <img src="images/tensor/3-axis_block.png"/>
  </td>
</tr>

</table>

### Getting a `tf.Tensor` object's rank

To determine the rank of a `tf.Tensor` object, call the `tf.rank` method.

In [12]:
my_image = tf.zeros([10, 299, 299, 3])  # batch x height x width x color
r = tf.rank(my_image)
print(r)

tf.Tensor(4, shape=(), dtype=int32)


## About shapes
shape指的是Tensor集合(array)的維度(dimensions)數量，還有各維度的大小，有時可以有彈性不用指定全部的維度大小，留待runtime才決定。
* **Shape**: The length (number of elements) of each of the axes of a tensor.
* **Rank**: Number of tensor axes.  A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
* **Axis** or **Dimension**: A particular dimension of a tensor.
* **Size**: The total number of items in the tensor, the product shape vector.

In [13]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

In [14]:
print("Type of every element:", rank_4_tensor.dtype)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])

Type of every element: <dtype: 'float32'>
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5


While axes are often referred to by their indices, you should always keep track of the meaning of each. Often axes are ordered from global to local: The batch axis first, followed by spatial dimensions, and features for each location last. This way feature vectors are contiguous regions of memory.

<table>
<tr>
<th>Typical axis order</th>
</tr>
<tr>
    <td>
<img src="images/tensor/shape2.png" alt="Keep track of what each axis is. A 4-axis tensor might be: Batch, Width, Height, Features">
  </td>
</tr>
</table>

<table>
<tr>
  <th colspan=2>A rank-4 tensor, shape: <code>[3, 2, 4, 5]</code></th>
</tr>
<tr>
  <td>
<img src="images/tensor/shape.png" alt="A tensor shape is like a vector.">
    <td>
<img src="images/tensor/4-axis_block.png" alt="A 4-axis tensor">
  </td>
  </tr>
</table>

## Shape

The **shape** of a tensor is the **number of elements** in each dimension.
TensorFlow automatically infers shapes during graph construction. These inferred
shapes might have known or unknown rank. If the rank is known, the sizes of each
dimension might be known or unknown.

The TensorFlow documentation uses three notational conventions to describe
tensor dimensionality: rank, shape, and dimension number. The following table
shows how these relate to one another:

Rank | Shape | Dimension number | Example
--- | --- | --- | ---
0 | [] | 0-D | A 0-D tensor.  A scalar.
1 | [D0] | 1-D | A 1-D tensor with shape [5].
2 | [D0, D1] | 2-D | A 2-D tensor with shape [3, 4].
3 | [D0, D1, D2] | 3-D | A 3-D tensor with shape [1, 4, 3].
n | [D0, D1, ... Dn-1] | n-D | A tensor with shape [D0, D1, ... Dn-1].

Shapes can be represented via Python lists / tuples of ints, or with the
`tf.TensorShape`.


## About value

### Graph

A **computational graph** is a series of TensorFlow operations arranged into a
graph. The graph is composed of two types of objects.

  * `tf.Tensor`: The edges in the graph. These represent the values
    that will flow through the graph. Most TensorFlow functions return
    `tf.Tensors`.
  * `tf.Operation` (or "ops"): The nodes of the graph.
    Operations describe calculations that consume and produce tensors.
    
![graph](https://www.tensorflow.org/images/tensors_flowing.gif)

* 上圖就為tensorflow 圖(graph)：在tensorflow中代表整個程序的結構或是欲執行的計算任務
* 上圖一個個的節點為tensorflow中的operation(op)

    * 專門進行運算的操作節點
    * 所有操作都是一個op

* 圖(graph)需要會話(session)才能運作



Important: `tf.Tensors` do not have values, they are just handles to elements
in the computation graph.

Let's build a simple computational graph. The most basic operation is a
constant. The Python function that builds the operation takes a tensor value as
input. The resulting operation takes no inputs. When run, it outputs the
value that was passed to the constructor. We can create two floating point
constants `a` and `b` as follows:

In [15]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(7.0, shape=(), dtype=float32)


有些特別的Tensor物件分別是:

  * `tf.constant`常數（Constant)
  * `tf.Variable`變數（Variable）
  * `tf.placeholder`佔位符(Placeholder) 
  * `tf.SparseTensor`稀疏張量(SparseTensor)
  
其中Variable最特別

* 一般來說tensor是不可更改的物件(immutable)，但是Variable是特別的tensor物件，他具有assign方法，可以更改狀態。tensor沒有assign方法。
* Variable可用於儲存網路內wieght等變數，而Tensor存放的是計算中間過程的結果。

# 常數（Constant）

In [16]:
#In Python, constants are written in all capital letters
print("Python:")
A = 19
B = 3
print(A + B)
print(A - B)
print(A * B)
print(A / B)
print(A** B)
print(A % B)
print(A// B)

Python:
22
16
57
6.333333333333333
6859
1
6


Tensor數值運算這些函數都必須在 TensorFlow 的 Eager Execution 模式中執行直接就有運算結果的輸出。

* 加 +：tf.add()
* 減 -： tf.sub()
* 乘 *： tf.multiply()
* 除 /： tf.divide()
* 次方 **： tf.pow()

In [17]:
x = tf.constant(19)
y = tf.constant(3)

print("TensorFlow:")
print( tf.add(x, y) )
print( tf.subtract(x, y) )
print( tf.multiply(x, y) )
print( tf.divide(x, y) )
print( tf.pow(x, y) )

TensorFlow:
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(57, shape=(), dtype=int32)
tf.Tensor(6.333333333333333, shape=(), dtype=float64)
tf.Tensor(6859, shape=(), dtype=int32)


常用的常數張量建構函數有:
* tf.zeros() ：建構內容數值皆為 0 的常數向量
* tf.ones() ：建構內容數值皆為 1 的常數向量
* tf.fill() ：建構內容數值皆為特定值的常數向量
* tf.range() ：建構內容數值為 (start, limit, delta) 數列的常數向量
* tf.random_normal() ：建構內容數值為符合常態分佈數列的常數向量
* tf.random_uniform() ：建構內容數值為符合均勻分佈數列的常數向量

常用的矩陣運算函數有:
* tf.reshape() ：調整矩陣外觀
* tf.eye() ：建構單位矩陣
* tf.diag() ：建構對角矩陣
* tf.matrix_transpose() ：轉置矩陣
* tf.matmul() ：矩陣相乘

In [18]:
print("NumPy:")
print(np.zeros((2, 2)))
print(np.ones((2, 2)))
print(np.full((2, 2), 5))
print(np.arange(1, 9, 2).reshape(2, 2))
print(np.random.normal(size=(2, 2)))
print(np.random.uniform(size=(2, 2)))

print(np.eye(2))
print(np.diag(np.arange(4)))
print(np.ones((2, 3)).T)
print(np.dot(np.arange(4).reshape(2, 2), np.arange(4).reshape(2, 2)))

NumPy:
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[5 5]
 [5 5]]
[[1 3]
 [5 7]]
[[1.92339595 0.00951787]
 [0.35296491 0.1388797 ]]
[[0.33344648 0.29404471]
 [0.76024473 0.73728698]]
[[1. 0.]
 [0. 1.]]
[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[ 2  3]
 [ 6 11]]


In [19]:
print("TensorFlow:")
zeros = tf.zeros((2, 2))
ones = tf.ones((2, 2))
fills = tf.fill((2, 2), 5)
ranges = tf.reshape(tf.range(1, 9, 2), (2, 2))
normals = tf.random.normal((2, 2))
uniforms = tf.random.uniform((2, 2))
eye = tf.eye(2)
diag = tf.linalg.diag(tf.range(4))
transpose = tf.linalg.matrix_transpose(tf.ones((2, 3)))
x = tf.reshape(tf.range(4), (2, 2))
multiply = tf.matmul(x, x)
matrice = [eye, diag, transpose, multiply]
initializations = [zeros, ones, fills, ranges, normals, uniforms, eye, diag, transpose, multiply]

for i in initializations:
    print(i)

TensorFlow:
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5 5]
 [5 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 3]
 [5 7]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.26594338 0.92482674]
 [0.9445926  0.815058  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.23030174 0.96823967]
 [0.16529226 0.49136364]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 2  3]
 [ 6 11]], shape=(2, 2), dtype=int32)


# 變數（Variable）

程式設計中為了保持彈性，必須將值賦與給變數（Variables），讓使用者能夠動態地進行相同的計算來得到不同的結果，這在 TensorFlow 中是以 tf.Variable() 來完成。

但宣告變數張量並不如 Python 或者先前宣告常數張量那麼單純，它需要兩個步驟：

1. 宣告變數張量的初始值、類型與外觀
2. 初始化變數張量

In [20]:
var_py = 47
print("Python:")
print(var_py)

Python:
47


In [21]:
# TensorFlow: FailedPreconditionError
var_tf = tf.Variable(47)
print("TensorFlow:")
print(var_tf)

TensorFlow:
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=47>


初始化成功後的變數張量，可以透過 .assign() 方法重新賦予不同值。

重新賦値這件事對 TensorFlow 來說也是一個運算，必須在宣告之後放入 Session 中執行，否則重新賦值並不會有作用。

重新賦值時必須要注意類型，賦予不同類型的值會得到 TypeError。

不僅是值的類型，外觀也必須跟當初所宣告的相同，賦予不同外觀的值會得到 ValueError。

In [22]:
var_tf = tf.Variable(47)
print('Before assign',var_tf)

var_tf.assign(24)
print('After assign',var_tf)


Before assign <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=47>
After assign <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=24>
